title:             Betelgeuse Project
email:             pramestiputri79@gmail.com
description:       Kindness, Humility, and Bonds
author:            Pramesty Putri
#url:               "localhost:4000"
url:               "http://sirius___ten.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
